In [18]:
import pandas as pd
import re
from sentence_transformers import SentenceTransformer, util

/Users/victorg/miniforge3/envs/rncp/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [19]:
cleandf = pd.read_csv("cleangames.csv")

In [20]:
cleandf

,id,category,first_release_date,name,platforms,rating,release_dates,slug,summary,genres
0,269473,0,1.696550e+09,Resonite,"[3, 6, 163]",100.000000,"[522725, 522726, 522727]",resonite--1,enter a novel digital universe with infinite p...,NaN
1,264773,0,1.695773e+09,Lizards Must Die,[6],99.798620,[517965],lizards-must-die,the great exploits of the ancient rus in the w...,"[25, 32]"
2,173172,3,1.632787e+09,Outer Wilds: Archaeologist Edition,"[6, 48, 49, 130, 167, 169]",99.655340,"[317893, 317894, 317895, 536374, 536745, 53674...",outer-wilds-archaeologist-edition,outer wilds archaeologist edition contains out...,"[9, 31, 32]"
3,46147,0,6.783264e+08,Golden Axe Warrior,[64],99.576263,"[188124, 437283]",golden-axe-warrior,world peace is at stake death adder a wicked g...,[12]
4,135341,0,1.544746e+09,Adastra,"[3, 6, 14, 34]",99.554056,"[376902, 376903, 376904, 376905]",adastra,after being kidnapped by a wolflike alien a ma...,[34]
...,...,...,...,...,...,...,...,...,...,...
248707,146,2,1.115251e+09,Star Wars Galaxies: Rage of the Wookiees,[6],NaN,[124710],star-wars-galaxies-rage-of-the-wookiees,star wars galaxies rage of the wookiees was th...,[12]
248708,110,0,7.258464e+08,Freddy Pharkas: Frontier Pharmacist,"[6, 13, 14]",NaN,"[298, 299, 300]",freddy-pharkas-frontier-pharmacist,the adventures of freddy pharkas a pharmacist ...,"[2, 31]"
248709,88,0,1.008288e+09,Frank Herbert's Dune,"[6, 8]",NaN,"[31040, 31041, 31042]",frank-herbert-s-dune,in the year the houses atreides and harkonnen ...,"[9, 31]"
248710,48,0,1.245715e+09,Overlord: Minions,[20],NaN,[792],overlord-minions,meet giblet blaze stench and zap an elite mini...,"[9, 25]"
248711,47,0,1.245715e+09,Overlord: Dark Legend,[5],NaN,"[791, 142019, 142020]",overlord-dark-legend,dark legend is a spinoff of the video game ove...,"[25, 31]"

In [21]:
# Chargement du modÃ¨le Sentence Transformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Chargement des donnÃ©es de jeux depuis cleangames.csv
games = cleandf[['name', 'summary']].to_dict('records')

# Encodage des descriptions de jeux
games_embeddings = model.encode([game['summary'] for game in games], convert_to_tensor=True)

/Users/victorg/miniforge3/envs/rncp/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(